Negrito/Models/Contato.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Negrito.Models
{
    [Table("Contato")]

    public class Contato
    {
        [Key]

        [Column("IDContato")]
        [Display(Name = "IDContato")]
        [Required]
        public int IDContato { get; set; }

        [Column(TypeName = "nvarchar(50)")]
        [Display(Name = "Nome")]
        [Required(ErrorMessage = "Campo obrigatório")]
        public string Nome { get; set; }

        [Column(TypeName = "nvarchar(50)")]
        [Display(Name = "Email")]
        [Required(ErrorMessage = "Campo obrigatório")]
        public string Email { get; set; }

        [Column(TypeName = "nvarchar(15)")]
        [Display(Name = "Telefone")]
        [Required(ErrorMessage = "Campo obrigatório")]
        public string Telefone { get; set; }

        [Column(TypeName = "nvarchar(500)")]
        [Display(Name = "Mensagem")]
        [Required(ErrorMessage = "Escreva o motivo do contato")]

        public string Mensagem { get; set; }


    }
}

Negrito/Controllers/ContatoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Negrito.Data;
using Negrito.Models;

namespace Negrito.Controllers
{
    public class ContatoesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ContatoesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Contatoes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Contato.ToListAsync());
        }

        // GET: Contatoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contato = await _context.Contato
                .FirstOrDefaultAsync(m => m.IDContato == id);
            if (contato == null)
            {
                return NotFound();
            }

            return View(contato);
        }

        // GET: Contatoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Contatoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IDContato,Nome,Email,Telefone,Mensagem")] Contato contato)
        {
            if (ModelState.IsValid)
            {
                _context.Add(contato);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(contato);
        }

        // GET: Contatoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contato = await _context.Contato.FindAsync(id);
            if (contato == null)
            {
                return NotFound();
            }
            return View(contato);
        }

        // POST: Contatoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IDContato,Nome,Email,Telefone,Mensagem")] Contato contato)
        {
            if (id != contato.IDContato)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contato);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContatoExists(contato.IDContato))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(contato);
        }

        // GET: Contatoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contato = await _context.Contato
                .FirstOrDefaultAsync(m => m.IDContato == id);
            if (contato == null)
            {
                return NotFound();
            }

            return View(contato);
        }

        // POST: Contatoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contato = await _context.Contato.FindAsync(id);
            _context.Contato.Remove(contato);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContatoExists(int id)
        {
            return _context.Contato.Any(e => e.IDContato == id);
        }
    }
}

Negrito/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Negrito.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Negrito.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Beneficiario()
        {
            return View();
        }

        public IActionResult Especialista()
        {
            return View();
        }

        public IActionResult Contato()
        {
            return View();
        }

      

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Negrito/Controllers/PacientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Negrito.Data;
using Negrito.Models;

namespace Negrito.Controllers
{
    public class PacientesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PacientesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Pacientes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Paciente.ToListAsync());
        }

        // GET: Pacientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paciente = await _context.Paciente
                .FirstOrDefaultAsync(m => m.IDPaciente == id);
            if (paciente == null)
            {
                return NotFound();
            }

            return View(paciente);
        }

        // GET: Pacientes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pacientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IDPaciente,Nome,Email,CPF,RG,Data_Nascimento_Pac,Endereço,Bairro,Cidade,Estado,Telefone")] Paciente paciente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(paciente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(paciente);
        }

        // GET: Pacientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paciente = await _context.Paciente.FindAsync(id);
            if (paciente == null)
            {
                return NotFound();
            }
            return View(paciente);
        }

        // POST: Pacientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IDPaciente,Nome,Email,CPF,RG,Data_Nascimento_Pac,Endereço,Bairro,Cidade,Estado,Telefone")] Paciente paciente)
        {
            if (id != paciente.IDPaciente)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(paciente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PacienteExists(paciente.IDPaciente))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(paciente);
        }

        // GET: Pacientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paciente = await _context.Paciente
                .FirstOrDefaultAsync(m => m.IDPaciente == id);
            if (paciente == null)
            {
                return NotFound();
            }

            return View(paciente);
        }

        // POST: Pacientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var paciente = await _context.Paciente.FindAsync(id);
            _context.Paciente.Remove(paciente);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PacienteExists(int id)
        {
            return _context.Paciente.Any(e => e.IDPaciente == id);
        }
    }
}

Negrito/Views/Home/Beneficiario.cshtml
@{
    ViewData["Title"] = "Beneficiario";
}
<h1>Saiba como ser atendido por um profissional da saúde mental</h1>

<p>Faça seu cadastro e busque uma pessoa especialista em saúde da mente</p>

    <!-- ====== Beneficiario Section ====== -->
    <section id="beneficiario" class="beneficiario">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 order-1 order-lg-2 beneficiario-img">
          <img src="~/Images/therapy.png" class="img-fluid" alt="">
          </div>
        <div class="col-lg-6 pt-4 pt-lg-0 content">
        <h3>Pronto para começar sua jornada no bem-estar mental?</h3>
          <p class="fst-italic">
            Veja em nosso mapa abaixo onde encontrar lugar para atendimento com profissionais da saúde mental.
          </p>
          <ul>
            <li><i class="bi bi-check-circle"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat</li>
            <li><i class="bi bi-check-circle"></i> Duis aute irure dolor in reprehenderit in voluptate velit</li>
            <li><i class="bi bi-check-circle"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate trideta storacalaperda</li>
          </ul>
          <p>
            Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
              velit esse cillum dolore eu fugiat nulla pariatur.
          </p>
        </div>
       </div>
      </div>
    </section>
    <!-- End Beneficiario Section -->

    <!-- ====== Cta Section ====== -->
    <section id="cta" class="cta d-flex align-items-center">
      <div class="container">

        <div class="text-center">
          <h3>Faça aqui seu cadastro</h3>
          <p> Responda o formulário para receber um email atualizado todos os meses com a lista de lugares na sua cidade que possuem atendimento para a saúde mental que oferecem serviços gratuitos ou a valor social.</p>
          <a asp-area="" asp-controller="Pacientes" asp-action="Create" class="cta-btn">Cadastro</a>
        </div>

      </div>
    </section>
    <!-- End Cta Section -->

    <!-- ===== Mapa Section ===== -->
    <section>
    <link rel="stylesheet" type="text/css" href="./style.css" />
    <script src="./site.js"></script>
   
    <h3>Onde encontrar consultas gratuitas ou a valor social na sua cidade</h3>
    <!--The div element for the map -->
    <div id="map"></div>

    <!-- Async script executes immediately and must be after any DOM elements used in callback. -->
    <script
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBoHYyAAscHMEYpJOt99X7LMY61ioZWeZc&callback=initMap"
      async
    ></script>
    </section>
    <!------ End Mapa Section ------->

    <!-- ====== Profissionais Section ====== -->
    <section id="profissionais" class="profissionais section-bg">
    <div class="container">

        <div class="section-title">
          <h2>Atendimentos</h2>
          <p>Atendimentos gratuitos ou a valores sociais que já estão cadastrados em nossa plataforma</p>
        </div>

        <div class="row">
          <div class="col-lg-4 col-md-6 d-flex align-items-stretch">
            <div class="member">
              <img src="assets/img/team/team-1.jpg" alt="">
              <h4>Serviço de Apoio Psicológico Remoto</h4>
              <span>Aracaju</span>
              <span2>Sergipe</span2>
              <p>
                (79) 3304-3599 ou 0800 729-3534, de segunda a sexta-feira, das 8h às 20h - Gratuito
              </p>
            </div>
            </div>

          <div class="col-lg-4 col-md-6 d-flex align-items-stretch">
            <div class="member">
              <img src="assets/img/team/team-2.jpg" alt="">
              <h4>Cuidados Psicológicos no Contexto da Pandemia</h4>
              <span>Belo Horizonte</span>
              <span2>Minas Gerais</span2>
              <p>
                Os Agendamentos das consultas devem ser feitos nos centros de saúde de BH - Gratuito
              </p>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 d-flex align-items-stretch">
            <div class="member">
              <img src="assets/img/team/team-3.jpg" alt="">
              <h4>Associação Paranaense de Terapia Familiar</h4>
              <span>Curitiba</span>
              <span2>Paraná</span2>
              <p>Gratuito</p>
            </div>
          </div>
        </div>
      </div>
   </section>
   <!-- End Profissionais Section -->

Negrito/Views/Home/Contato.cshtml
@{
    ViewData["Title"] = "Contato";
}
<h1>@ViewData["Title"]</h1>

<p>Perguntas Frequentes (escrever perguntas e respostas aqui)</p>

<div class="accordion" id="accordionExample">
    <div class="card">
        <div class="card-header" id="headingOne">
            <h5 class="mb-0">
                <button class="btn btn-link" style="color: #8C52FF" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    Pergunta 1
                </button>
            </h5>
        </div>

        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
            <div class="card-body">
                Resposta 1 - Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch.
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header" id="headingTwo">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" style="color: #8C52FF" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    Pergunta 2
                </button>
            </h5>
        </div>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
            <div class="card-body">
                Resposta 2 - Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch.
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header" id="headingThree">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" style="color: #8C52FF" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                    Resposta 3
                </button>
            </h5>
        </div>
        <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
            <div class="card-body">
                Resposta 3 - Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch.
            </div>
        </div>
    </div>
</div>

<div class="section-title">
    <h2>Possui alguma dúvida ou sugestão para nos dar?</h2>
    <p>Indique o assunto que entraremos em contato</p>
    <a asp-area="" asp-controller="Contatoes" asp-action="Create" class="cta-btn">Contato</a>
</div>

Negrito/Views/Home/Especialista.cshtml
@{
    ViewData["Especialista"] = "Especialista";
}
<h1>@ViewData["Especialista "]</h1>

<p>Faça seu cadastro e crie sua agenda de atendimento</p>

<section id="especialista" class="especialista">
    <div class="container">
        <div class="row">
          <div class="col-lg-6 especialista-img">
            <img src="~/Images/therapy.png" class="img-fluid" alt="">
          </div>
          <div class="col-lg-6 pt-4 pt-lg-0 content">
            <h3>É um profissional da saúde mental alinhado à proposta da NEGRITO?</h3>
            <p class="fst-italic">
              Faça seu cadastro que entraremos em contato.
            </p>
           </div>
        </div>
    </div>>
</section>

Negrito/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<section id="capa" class="d-flex align-items-center">
<div class="container">
      <div class="row">
        <div class="col-lg-6 order-1 order-lg-2 capa-img">
          <img src="~/Images/therapy.png" class="img-fluid" alt="">
        </div>
        <div class="col-md-6 pt-5 pt-lg-0 order-2 order-lg-1 d-flex flex-column content">
          <h1>Ser visto, ser ouvido e ser compreendido.</h1>
          <h2>Saúde mental não deve ser um privilégio</h2>
          <div class="d-flex">
            <a href="Home/Beneficiario" class="btn-get-started scrollto">Encontre um local para ser atendido</a>
          </div>
        </div>  
      </div>
</div>
</section>
<!-- End Capa -->
      <div class="section-title">
          <h2>A saúde mental da população negra importa!</h2>
          <p>O grito de um é a soma do grito de muitos.<p/>
          <p>A NEGRITO grita utilizando-se da escuta e facilitação no acesso aos cuidados da saúde mental da população negra.</p>
          <p>NEGRITO apresenta-se como um espaço virtual dedicado a incentivar o bem-estar das pessoas negras, auxiliando-as a encontrar profissionais negros e/ou com competências multiculturais a valores sociais.</p>
          <p></p>
      </div>